yversion: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-caredb}
      POSTGRES_USER: ${DB_USER:-careuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-carepass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: